import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/user.dart';
import '../models/reminder.dart';
import '../models/chat_message.dart';
import '../models/mochi_device.dart';

class LocalStorageService extends ChangeNotifier {
  static const String userBoxName = 'userBox';
  static const String reminderBoxName = 'reminderBox';
  static const String chatBoxName = 'chatBox';
  static const String deviceBoxName = 'deviceBox';
  static const String settingsKey = 'settings';
  
  late Box<User> _userBox;
  late Box<Reminder> _reminderBox;
  late Box<ChatMessage> _chatBox;
  late Box _deviceBox;
  late SharedPreferences _prefs;
  
  bool _isInitialized = false;
  User? _currentUser;
  
  // Getters
  bool get isInitialized => _isInitialized;
  User? get currentUser => _currentUser;
  
  /// Initialize all storage boxes
  Future<void> initialize() async {
    try {
      // Initialize Hive
      await Hive.initFlutter();
      
      // Register adapters (generated by build_runner)
      if (!Hive.isAdapterRegistered(0)) {
        Hive.registerAdapter(UserAdapter());
      }
      if (!Hive.isAdapterRegistered(1)) {
        Hive.registerAdapter(ReminderAdapter());
      }
      if (!Hive.isAdapterRegistered(2)) {
        Hive.registerAdapter(ChatMessageAdapter());
      }
      
      // Open boxes
      _userBox = await Hive.openBox<User>(userBoxName);
      _reminderBox = await Hive.openBox<Reminder>(reminderBoxName);
      _chatBox = await Hive.openBox<ChatMessage>(chatBoxName);
      _deviceBox = await Hive.openBox(deviceBoxName);
      
      // Initialize SharedPreferences
      _prefs = await SharedPreferences.getInstance();
      
      // Load current user
      _loadCurrentUser();
      
      _isInitialized = true;
      notifyListeners();
      
      debugPrint("Storage: Service initialized successfully");
    } catch (e) {
      debugPrint("Storage: Initialization error: $e");
    }
  }

  /// Load current user from storage
  void _loadCurrentUser() {
    try {
      if (_userBox.isNotEmpty) {
        _currentUser = _userBox.getAt(0);
      }
    } catch (e) {
      debugPrint("Storage: Load user error: $e");
    }
  }

  // ============ USER MANAGEMENT ============

  /// Save user data
  Future<void> saveUser(User user) async {
    try {
      await _userBox.clear();
      await _userBox.add(user);
      _currentUser = user;
      notifyListeners();
      debugPrint("Storage: User saved successfully");
    } catch (e) {
      debugPrint("Storage: Save user error: $e");
    }
  }

  /// Update user preferences
  Future<void> updateUserPreferences({
    String? selectedTheme,
    String? selectedVoice,
    String? preferredLanguage,
    bool? soundEffectsEnabled,
    bool? animationsEnabled,
    bool? festivalModeEnabled,
    bool? petModeEnabled,
  }) async {
    if (_currentUser == null) return;
    
    try {
      final updatedUser = User(
        fullName: _currentUser!.fullName,
        nickname: _currentUser!.nickname,
        dateOfBirth: _currentUser!.dateOfBirth,
        profileImage: _currentUser!.profileImage,
        preferredLanguage: preferredLanguage ?? _currentUser!.preferredLanguage,
        soundEffectsEnabled: soundEffectsEnabled ?? _currentUser!.soundEffectsEnabled,
        animationsEnabled: animationsEnabled ?? _currentUser!.animationsEnabled,
        selectedTheme: selectedTheme ?? _currentUser!.selectedTheme,
        selectedVoice: selectedVoice ?? _currentUser!.selectedVoice,
        festivalModeEnabled: festivalModeEnabled ?? _currentUser!.festivalModeEnabled,
        petModeEnabled: petModeEnabled ?? _currentUser!.petModeEnabled,
      );
      
      await saveUser(updatedUser);
    } catch (e) {
      debugPrint("Storage: Update user preferences error: $e");
    }
  }

  /// Check if user exists
  bool hasUser() {
    return _currentUser != null;
  }

  // ============ REMINDER MANAGEMENT ============

  /// Save reminder
  Future<void> saveReminder(Reminder reminder) async {
    try {
      await _reminderBox.add(reminder);
      notifyListeners();
      debugPrint("Storage: Reminder saved: ${reminder.title}");
    } catch (e) {
      debugPrint("Storage: Save reminder error: $e");
    }
  }

  /// Update reminder
  Future<void> updateReminder(String reminderId, Reminder updatedReminder) async {
    try {
      final index = _reminderBox.values.toList().indexWhere((r) => r.id == reminderId);
      if (index != -1) {
        await _reminderBox.putAt(index, updatedReminder);
        notifyListeners();
        debugPrint("Storage: Reminder updated: ${updatedReminder.title}");
      }
    } catch (e) {
      debugPrint("Storage: Update reminder error: $e");
    }
  }

  /// Delete reminder
  Future<void> deleteReminder(String reminderId) async {
    try {
      final index = _reminderBox.values.toList().indexWhere((r) => r.id == reminderId);
      if (index != -1) {
        await _reminderBox.deleteAt(index);
        notifyListeners();
        debugPrint("Storage: Reminder deleted: $reminderId");
      }
    } catch (e) {
      debugPrint("Storage: Delete reminder error: $e");
    }
  }

  /// Get all reminders
  List<Reminder> getAllReminders() {
    try {
      return _reminderBox.values.toList();
    } catch (e) {
      debugPrint("Storage: Get reminders error: $e");
      return [];
    }
  }

  /// Get active reminders
  List<Reminder> getActiveReminders() {
    try {
      return _reminderBox.values
          .where((reminder) => reminder.isActive)
          .toList()
        ..sort((a, b) => a.scheduledTime.compareTo(b.scheduledTime));
    } catch (e) {
      debugPrint("Storage: Get active reminders error: $e");
      return [];
    }
  }

  /// Get upcoming reminders (next 24 hours)
  List<Reminder> getUpcomingReminders() {
    try {
      final now = DateTime.now();
      final tomorrow = now.add(const Duration(days: 1));
      
      return _reminderBox.values
          .where((reminder) => 
              reminder.isActive &&
              reminder.scheduledTime.isAfter(now) &&
              reminder.scheduledTime.isBefore(tomorrow))
          .toList()
        ..sort((a, b) => a.scheduledTime.compareTo(b.scheduledTime));
    } catch (e) {
      debugPrint("Storage: Get upcoming reminders error: $e");
      return [];
    }
  }

  /// Mark reminder as completed
  Future<void> completeReminder(String reminderId) async {
    try {
      final index = _reminderBox.values.toList().indexWhere((r) => r.id == reminderId);
      if (index != -1) {
        final reminder = _reminderBox.getAt(index)!;
        final completedReminder = Reminder(
          id: reminder.id,
          title: reminder.title,
          description: reminder.description,
          scheduledTime: reminder.scheduledTime,
          isActive: false,
          isRepeating: reminder.isRepeating,
          repeatPattern: reminder.repeatPattern,
          notifyOnMochi: reminder.notifyOnMochi,
          createdAt: reminder.createdAt,
          completedAt: DateTime.now(),
          priority: reminder.priority,
          emoji: reminder.emoji,
        );
        
        await _reminderBox.putAt(index, completedReminder);
        notifyListeners();
        debugPrint("Storage: Reminder completed: ${reminder.title}");
      }
    } catch (e) {
      debugPrint("Storage: Complete reminder error: $e");
    }
  }

  // ============ CHAT MANAGEMENT ============

  /// Save chat message
  Future<void> saveChatMessage(ChatMessage message) async {
    try {
      await _chatBox.add(message);
      notifyListeners();
      debugPrint("Storage: Chat message saved");
    } catch (e) {
      debugPrint("Storage: Save chat message error: $e");
    }
  }

  /// Get all chat messages
  List<ChatMessage> getAllChatMessages() {
    try {
      return _chatBox.values.toList()
        ..sort((a, b) => a.timestamp.compareTo(b.timestamp));
    } catch (e) {
      debugPrint("Storage: Get chat messages error: $e");
      return [];
    }
  }

  /// Get recent chat messages (last 50)
  List<ChatMessage> getRecentChatMessages({int limit = 50}) {
    try {
      final messages = _chatBox.values.toList()
        ..sort((a, b) => b.timestamp.compareTo(a.timestamp));
      
      return messages.take(limit).toList().reversed.toList();
    } catch (e) {
      debugPrint("Storage: Get recent chat messages error: $e");
      return [];
    }
  }

  /// Clear all chat history
  Future<void> clearChatHistory() async {
    try {
      await _chatBox.clear();
      notifyListeners();
      debugPrint("Storage: Chat history cleared");
    } catch (e) {
      debugPrint("Storage: Clear chat history error: $e");
    }
  }

  /// Clear old chat messages (keep last 100)
  Future<void> clearOldChatMessages() async {
    try {
      final messages = _chatBox.values.toList()
        ..sort((a, b) => b.timestamp.compareTo(a.timestamp));
      
      if (messages.length > 100) {
        await _chatBox.clear();
        for (int i = 0; i < 100; i++) {
          await _chatBox.add(messages[i]);
        }
        notifyListeners();
        debugPrint("Storage: Old chat messages cleared");
      }
    } catch (e) {
      debugPrint("Storage: Clear old chat messages error: $e");
    }
  }

  // ============ DEVICE MANAGEMENT ============

  /// Save Mochi device data
  Future<void> saveMochiDevice(MochiDevice device) async {
    try {
      await _deviceBox.put('mochi_device', device.toJson());
      debugPrint("Storage: Mochi device saved");
    } catch (e) {
      debugPrint("Storage: Save Mochi device error: $e");
    }
  }

  /// Get saved Mochi device
  MochiDevice? getSavedMochiDevice() {
    try {
      final deviceData = _deviceBox.get('mochi_device');
      if (deviceData != null) {
        return MochiDevice.fromJson(Map<String, dynamic>.from(deviceData));
      }
      return null;
    } catch (e) {
      debugPrint("Storage: Get Mochi device error: $e");
      return null;
    }
  }

  // ============ SETTINGS MANAGEMENT ============

  /// Save app settings
  Future<void> saveSettings(Map<String, dynamic> settings) async {
    try {
      final settingsJson = Map<String, dynamic>.from(settings)
          .map((key, value) => MapEntry(key, value.toString()));
      
      for (final entry in settingsJson.entries) {
        await _prefs.setString('${settingsKey}_${entry.key}', entry.value);
      }
      
      debugPrint("Storage: Settings saved");
    } catch (e) {
      debugPrint("Storage: Save settings error: $e");
    }
  }

  /// Get app settings
  Map<String, dynamic> getSettings() {
    try {
      final settings = <String, dynamic>{};
      final keys = _prefs.getKeys().where((key) => key.startsWith('${settingsKey}_'));
      
      for (final key in keys) {
        final settingKey = key.replaceFirst('${settingsKey}_', '');
        settings[settingKey] = _prefs.getString(key);
      }
      
      return settings;
    } catch (e) {
      debugPrint("Storage: Get settings error: $e");
      return {};
    }
  }

  /// Get specific setting
  String? getSetting(String key) {
    try {
      return _prefs.getString('${settingsKey}_$key');
    } catch (e) {
      debugPrint("Storage: Get setting error: $e");
      return null;
    }
  }

  /// Save specific setting
  Future<void> saveSetting(String key, String value) async {
    try {
      await _prefs.setString('${settingsKey}_$key', value);
    } catch (e) {
      debugPrint("Storage: Save setting error: $e");
    }
  }

  // ============ DATA CLEANUP ============

  /// Clear all data (for testing/reset)
  Future<void> clearAllData() async {
    try {
      await _userBox.clear();
      await _reminderBox.clear();
      await _chatBox.clear();
      await _deviceBox.clear();
      await _prefs.clear();
      
      _currentUser = null;
      notifyListeners();
      
      debugPrint("Storage: All data cleared");
    } catch (e) {
      debugPrint("Storage: Clear all data error: $e");
    }
  }

  /// Export user data
  Map<String, dynamic> exportUserData() {
    try {
      return {
        'user': _currentUser?.toJson(),
        'reminders': _reminderBox.values.map((r) => r.toJson()).toList(),
        'chatMessages': _chatBox.values.map((c) => c.toJson()).toList(),
        'device': getSavedMochiDevice()?.toJson(),
        'settings': getSettings(),
        'exportedAt': DateTime.now().toIso8601String(),
      };
    } catch (e) {
      debugPrint("Storage: Export data error: $e");
      return {};
    }
  }

  @override
  void dispose() {
    // Close boxes when service is disposed
    if (_isInitialized) {
      _userBox.close();
      _reminderBox.close();
      _chatBox.close();
      _deviceBox.close();
    }
    super.dispose();
  }
}